### ISSUE TITLE
Could not load 'guard/jruby-minitest' 

### ISSUE THREAD

**Issue by iDiogenes** [jackxxu/guard-jruby-minitest#1]
Thanks for this great gem! I have used guard-ruby-minitest for several months and it recently stopped working on all my jruby rack/rails apps. Just for fun I created a brand new rails project running jRuby1-7-19 and ran

```
bundle exec guard init jruby-minitest
```

The errors I received were:

```
ERROR - Could not load 'guard/jruby-minitest' or '~/.guard/templates/jruby-minitest' or find class Guard::Jrubyminitest
ERROR - Error is: No such file or directory @ rb_sysopen - ~/.guard/templates/jruby-minitest
```

My Gemfile looks like 

```
group :development do
  gem 'quiet_assets'
  gem 'guard'
  gem 'guard-minitest'
  gem 'guard-jruby-minitest'
end
```

and the relevant Gemfile.lock shows:

```
guard (2.12.5)
  formatador (>= 0.2.4)
  listen (~> 2.7)
  lumberjack (~> 1.0)
  nenv (~> 0.1)
  notiffany (~> 0.0)
  pry (>= 0.9.12)
  shellany (~> 0.0)
  thor (>= 0.18.1)
guard-jruby-minitest (0.1.10)
  guard (>= 0.10.0)
  guard-minitest (= 2.3.1)
  minitest
  ruby_parser (>= 3.0)
guard-minitest (2.3.1)
  guard (~> 2.0)
  minitest (>= 3.0)
```

Since this seems to have randomly stopped working my suspicion are around Guard being updated. Any help or suggestions would be appricaited.  Thanks!

**Comment by iDiogenes** [comment]
I found the issue - the version of jruby-minitest that guard-jruby-minitest is locked too requires lib/guard/guard.rb and that file has been removed after Guard version 2.7.2.

**Comment by jackxxu** [comment]
@iDiogenes, i just pushed a commit that locks the guard version to 2.6.1, which still has `lib/guard/guard.rb`. the new gem version is `0.1.11`. 

thanks for raising the issue. :bow:
